baseURL = "https://notes.carlo.dev/"
languageCode = "en-us"
title = "carlo's notes"
theme = "carlo"
paginate = 20

[markup]
  [markup.highlight]
    style = "dracula"
    lineNos = false
    codeFences = true
    noClasses = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

[params]
  author = "carlo"
  description = "notes on security, tooling, and whatever else"
