baseURL = "https://notes.carlo.dev/"
languageCode = "en-us"
title = "carlo's notes"
theme = "carlo"

[pagination]
  pagerSize = 10

[markup]
  [markup.highlight]
    style = "dracula"
    lineNos = false
    codeFences = true
    noClasses = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false
  [markup.goldmark.renderer]
    unsafe = true

[params]
  author = "carlo"
  description = "notes on security, tooling, and whatever else"
